# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puterea_efectului', models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], default=0, max_length=2)),
                ('medium_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=512)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'')),
                ('boala', models.ManyToManyField(to='first.Boala')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentPharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('farmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Farmacie')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Medicament')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating_value', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Medicament')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.User'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='medicine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.MedicineType'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='omologi',
            field=models.ManyToManyField(related_name='_medicament_omologi_+', to='first.Medicament'),
        ),
    ]
