# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='boala',
            field=models.ManyToManyField(null=True, to='first.Boala'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='omologi',
            field=models.ManyToManyField(null=True, related_name='_medicament_omologi_+', to='first.Medicament'),
        ),
    ]
