# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20160616_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='boala',
            field=models.ManyToManyField(blank=True, to='first.Boala'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='omologi',
            field=models.ManyToManyField(blank=True, related_name='_medicament_omologi_+', to='first.Medicament'),
        ),
    ]
